services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: gtfs
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gtfs-network

  redis:
    image: redis:7-alpine
    container_name: gtfs-realtime-redis
    ports:
      - "6379:6379"
    networks:
      - gtfs-network

  backend:
    build: .
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env.dev_docker
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    networks:
      - gtfs-network

  celery-worker:
    build: .
    command: watchmedo auto-restart --directory=/app --pattern=*.py --recursive -- celery -A src.tasks worker --loglevel=info
    env_file:
      - .env.dev_docker
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    networks:
      - gtfs-network

  celery-beat:
    build: .
    command: watchmedo auto-restart --directory=/app --pattern=*.py --recursive -- celery -A src.tasks beat --loglevel=info
    env_file:
      - .env.dev_docker
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    networks:
      - gtfs-network

volumes:
  pgdata:

networks:
  gtfs-network:
    external: true
