[project]
name = "gtfs-realtime"
version = "0.1.0"
description = "Python server implementation using gRPC to retrieve and stream realtime transit data using GTFS"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.18.5",
    "celery>=5.4.0",
    "fastapi[standard]>=0.139.2",
    "grpcio",
    "grpcio-tools",
    "gtfs-realtime-bindings",
    "psycopg2>=2.9.12",
    "psycopg2-binary",
    "redis>=5.2.1",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.51",
    "sse-starlette>=3.4.6",
    "uvicorn[standard]>=0.51.0",
    "watchdog>=6.0.0",
]

[tool.mypy]
plugins = ["pydantic.mypy"]
strict = true
ignore_missing_imports = true
