"""initial migration after squashing

Revision ID: 9013ab755a6b
Revises: 
Create Date: 2026-08-06 12:45:03.682389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9013ab755a6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transit_system',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('realtime_url', sa.String(), nullable=False),
    sa.Column('schedule_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uq_name')
    )
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transit_system_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('long_name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('text_color', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['transit_system_id'], ['transit_system.id'], ),
    sa.PrimaryKeyConstraint('id', 'short_name'),
    sa.UniqueConstraint('id', 'short_name', name='uq_route_short_name'),
    sa.UniqueConstraint('short_name'),
    sa.UniqueConstraint('short_name', name='uq_short_name')
    )
    op.create_table('stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('transit_system_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['transit_system_id'], ['transit_system.id'], ),
    sa.PrimaryKeyConstraint('id', 'stop_id'),
    sa.UniqueConstraint('stop_id', 'transit_system_id', name='uq_transit_stop_id')
    )
    op.create_table('transit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transit_system_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('trip_headsign', sa.String(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('stop_name', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('route_color', sa.String(), nullable=False),
    sa.Column('route_text_color', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['transit_system_id'], ['transit_system.id'], ),
    sa.PrimaryKeyConstraint('id', 'trip_id')
    )
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('transit_system_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id', 'trip_id'], ['trip.id', 'trip.trip_id'], ),
    sa.ForeignKeyConstraint(['transit_system_id'], ['transit_system.id'], ),
    sa.PrimaryKeyConstraint('id', 'trip_id'),
    sa.UniqueConstraint('transit_system_id', 'trip_id', name='uq_trip')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    op.drop_table('transit_log')
    op.drop_table('stop')
    op.drop_table('route')
    op.drop_table('transit_system')
    # ### end Alembic commands ###
